"""migration

Revision ID: fbe9bd807d82
Revises: cb79f2a8b63a
Create Date: 2024-08-13 11:25:04.357356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe9bd807d82'
down_revision: Union[str, None] = 'cb79f2a8b63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name2', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
