version: '3'

services:
  django:
    build: .
    container_name: django-cont
    #command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - '8001:8000'
    depends_on:
      - psql


  psql:
    image: postgres
    restart: always
    # set shared memавory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_HOST: psql
      POSTGRES_PORT: 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data: null